### ISSUE TITLE
Unhandled exception: Conversion from string "2018 6:00:01" to type 'Date' is not valid

### ISSUE THREAD

**Issue by sicklittlemonkey** [clinthuffman/PAL#17]
The log that caused this is 230MB.
But here's the exception dialog text.

Cheers,
NIck.

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.InvalidCastException: Conversion from string "2018 6:00:01" to type 'Date' is not valid.
>    at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(String Value)
>    at PALWizard.frmPALExecutionWizard.GetCounterLogInformation(Object sCounterLogFilePath)
>    at PALWizard.frmPALExecutionWizard.UpdateCheckBoxRestrictToDateTimeRange()
>    at PALWizard.frmPALExecutionWizard.CheckBoxRestrictToADateTimeRange_CheckedChanged(Object sender, EventArgs e)
>    at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
>    at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
>    at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
>    at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
> ----------------------------------------
> PALWizard
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/Program%20Files/PAL/PAL/PALWizard.exe
> ----------------------------------------
> Microsoft.VisualBasic
>     Assembly Version: 8.0.0.0
>     Win32 Version: 8.0.50727.8825 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
> ----------------------------------------
> System
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8827 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Runtime.Remoting
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
> ----------------------------------------
> PALFunctions
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/Program%20Files/PAL/PAL/PALFunctions.DLL
> ----------------------------------------
> System.Web
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
>     CodeBase: file:///C:/WINDOWS/assembly/GAC_64/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> 
> 
>

**Comment by clinthuffman** [comment]
Hi Nick,

Thanks. It looks like Relog.exe (part of the operating system) failed to apply a time restriction to the counter log and then PAL bubbled up the exception/error or the counter log is corrupted. I recommend that you open the log in Performance Monitor first to see if the log is corrupted or not. If not corrupted, then I recommend using Relog.exe manually to create a new counter log with the desired range and then have PAL process the new log without the time restriction.

Thank you,
Clint “The PAL<http://pal.codeplex.com/> guy” Huffman (clinth@microsoft.com<mailto:clinth@microsoft.com>)
Senior Software Engineer | Microsoft Surface Quality/Devices
OFFICE +1 425.706.8944 | MOBILE +1 425.577.0169
Author of Windows Performance Analysis Field Guide<http://amzn.to/1y1EMET>
Microsoft Corporation
Surface

**Comment by sicklittlemonkey** [comment]
Hi Clint.

The log wasn't corrupted, but thanks for the reminder - we've actually corresponded about relog errors before - years ago now. ; - )

This time it turns out relog now uses the system short date format (it even quotes what you've set it to in its command line help) and I'd changed mine to get the day of the week in my taskbar clock. But relog can't parse the DOW!

Here's the documentation issue I filed:
https://github.com/MicrosoftDocs/windowsserverdocs/issues/596

Cheers,
Nick.

**Comment by clinthuffman** [comment]
I'm not sure how to fix this. What do you recommend?

**Comment by sicklittlemonkey** [comment]
You should be able to reproduce by changing your short date format to ddd d/MM/yyyy. It seems you can't do this in the modern Settings UI in Windows 10, so you need to use the Control Panel->Clock and Region->Region->Change date, time or number formats->Formats tab, change the "Short date" entry.

But as for fixing it, I guess you can't since it's a bug in relog. Relog uses the short date format (as I said, if you get relog to print its help, the current short date format (e.g. with my ddd) is printed in the help) even though it can't handle ddd.

It would be nice if there was a warning for a non-standard short date format - if you can be bothered. ; - )
